# Generated by Django 3.2.8 on 2022-02-21 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_taskassign',
            name='department',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project_taskassign',
            name='designation',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
