# Generated by Django 3.2.8 on 2022-02-24 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0002_auto_20220221_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='designation',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='departmentbranch', to='base_app.department'),
        ),
    ]
